# Generated by Django 5.0.3 on 2024-03-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
    ]
