# Generated by Django 5.0.3 on 2024-03-15 20:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_user_is_employee_user_is_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('street', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('single', 'Single Room'), ('suite', 'Suite'), ('deluxe', 'Deluxe Room'), ('family', 'Family Room'), ('connecting', 'Connecting Rooms'), ('adjoining', 'Adjoining Rooms'), ('accessible', 'Accessible Room'), ('junior_suite', 'Junior Suite'), ('presidential_suite', 'Presidential Suite')], default='', max_length=200)),
                ('status', models.CharField(choices=[('AVA', 'Available'), ('OCC', 'Occupied'), ('MAI', 'Under Maintenance')], default='', max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('price_per_nigth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
