# Generated by Django 5.0.3 on 2024-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_code_booking_deleted_at_booking_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occuped', 'Occupied'), ('maintenance', 'Under Maintenance')], default='', max_length=100),
        ),
    ]
