# Generated by Django 5.0.3 on 2024-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_company_alter_hotel_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
