# Generated by Django 5.0.3 on 2024-03-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_quantity_days_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity_days',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
