# Generated by Django 5.0.3 on 2024-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_quantity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quantity_people',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
